name: Publish Package Learn
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Install
        run: mvn install
      - name: Publish package
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
      - name: Delete Old Package Versions
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: 'org.learn.ival'
          package-type: 'maven'
          min-versions-to-keep: 5

# name: Publish Package Jobseeker Entity
# on:
#   push:
#     branches: [master]

# jobs:
#   delete-package-versions:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Delete Package Versions
#         uses: actions/delete-package-versions@v5.0.0
#         with:
#           package-name: 'org.jobseeker.entity'
#           package-type: 'maven'
#           min-versions-to-keep: 5