name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          
      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "github-entity",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
          repositories: |
            [{
              "id": "github",
              "url": "https://maven.pkg.github.com/Jobseeker-company/entity-of-everything",
              "snapshots": {
                "enabled": "true"
              }
            }]

      - name: Build with Maven
        run: mvn -X clean install  # Added -X for debug output
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
