name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      # Add this to match your local settings.xml
      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [
              {
                "id": "github-entity",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.JAVA_TOKEN }}"  # Create this secret in your repo
              }
            ]
          repositories: |
            [
              {
                "id": "github-entity",
                "url": "https://maven.pkg.github.com/Jobseeker-company/entity-of-everything",
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]

      - name: Build and Deploy
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}